---
- name: Set message processor consistencylevel
  hosts: '{{ hosts }}'
  gather_facts: no
  serial: 1
  vars:
    cwc_properties:
    - { key: conf_keymanagement_kms_cache_memory_element_enable, value: '{{ enable_cache }}', file_name: '{{ property_file }}' }
  roles:
  - { role: apigee-opdk-cassandra-consistencylevel-modifier }
  - { role: apigee-opdk-cwc-update }

