---
- name: Update cache with server attributes
  include: configuration/update_cache.yml
  tags:
  - cache

- name: Rolling restart of all RMPs and MS
  hosts: rmp,ms
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - { role: apigee-opdk-stop-components, tags: ['pre_restart', 'pre_stop'] }
  - { role: apigee-opdk-start-components, tags: ['pre_restart', 'pre_start'], component_start_delay: '{{ start_delay | default(0) }}' }

- name: Change cassandra replication factor
  hosts: ds[0]
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  vars:
    cassandra_keyspaces:
    - auth
    - cache
    - devconnect
    - user_settings
    - apprepo
    - kms
    - scheduler
    - ax_custom_report_model
    - audit
    - aries
    - apimodel
    - edgenotification
    - analytics
    - keyvaluemap
    - counter
  roles:
  - { role: apigee-opdk-cassandra-change-replication-factor, tags: ['update'], keyspaces: '{{ cassandra_keyspaces }}' }

- name: Execute nodetool repair on Cassandra nodes
  hosts: ds
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - { role: apigee-opdk-cassandra-repair, tags: ['repair'] }

- name: Rolling restart of all RMPs and MS
  hosts: rmp,ms
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - { role: apigee-opdk-stop-components, tags: ['post_restart', 'post_stop'] }
  - { role: apigee-opdk-start-components, tags: ['post_restart', 'post_start'], component_start_delay: '{{ start_delay | default(0) }}' }
