---
- include: configuration/update_cache.yml

- hosts: '{{ hosts }}'
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  vars:
    keyspaces:
    - auth
    - cache
    - devconnect
    - user_settings
    - apprepo
    - kms
    - scheduler
    - ax_custom_report_model
    - audit
    - aries
    - apimodel
    - edgenotification
    - analytics
    - keyvaluemap
    - counter

  roles:
  - apigee-opdk-setup-default-settings
  - apigee-opdk-cassandra-change-replication-factor
  - apigee-opdk-cassandra-repair
  - apigee-opdk-stop-components
  - apigee-opdk-start-components


