---
- include: configuration/update_cache.yml
  tags:
  - cache

- hosts: ds
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - { role: apigee-opdk-cassandra-change-quorum, consistency: TWO }

- hosts: rmp
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - { role: apigee-opdk-stop-components, tags: ['restart', 'stop'] }
  - { role: apigee-opdk-start-components, tags: ['restart', 'start'], component_start_delay: '{{ start_delay | default(0) }}' }

- hosts: ds[0]
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  vars:
    cassandra_keyspaces:
    - auth
    - cache
    - devconnect
    - user_settings
    - apprepo
    - kms
    - scheduler
    - ax_custom_report_model
    - audit
    - aries
    - apimodel
    - edgenotification
    - analytics
    - keyvaluemap
    - counter
  roles:
  - { role: apigee-opdk-cassandra-change-replication-factor, tags: ['update'], keyspaces: '{{ cassandra_keyspaces }}' }


- hosts: ds
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - { role: apigee-opdk-cassandra-repair, tags: ['repair'] }

- hosts: ds
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - { role: apigee-opdk-cassandra-change-quorum, consistency: LOCAL_QUORUM }

- hosts: rmp
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - { role: apigee-opdk-stop-components, tags: ['restart', 'stop'] }
  - { role: apigee-opdk-start-components, tags: ['restart', 'start'], component_start_delay: '{{ start_delay | default(0) }}' }
