---
- src: https://github.com/carlosfrias/apigee-opdk-cassandra-change-replication-factor.git

- src: https://github.com/carlosfrias/apigee-opdk-cassandra-rebuild.git

- src: https://github.com/carlosfrias/apigee-opdk-stop-components.git

- src: https://github.com/carlosfrias/apigee-opdk-start-components.git

- src: https://github.com/carlosfrias/apigee-opdk-setup-default-settings.git

- src: https://github.com/carlosfrias/apigee-opdk-cache-update.git
