---
- src: https://github.com/carlosfrias/apigee-opdk-cassandra-change-replication-factor.git

- src: https://github.com/carlosfrias/apigee-opdk-cassandra-repair.git

- src: https://github.com/carlosfrias/apigee-opdk-cassandra-rebuild.git

- src: https://github.com/carlosfrias/apigee-opdk-stop-components.git

- src: https://github.com/carlosfrias/apigee-opdk-cassandra-shutdown-preparation.git

- src: https://github.com/carlosfrias/apigee-opdk-start-components.git

- src: https://github.com/carlosfrias/apigee-opdk-setup-status.git

- src: https://github.com/carlosfrias/apigee-opdk-setup-default-settings.git

- src: https://github.com/carlosfrias/apigee-opdk-cache-update.git

- src: https://github.com/carlosfrias/apigee-opdk-backup.git

- src: https://github.com/carlosfrias/apigee-opdk-cassandra-consistencylevel-modifier.git

- src: https://github.com/carlosfrias/apigee-fetch-files

- src: https://github.com/carlosfrias/apigee-opdk-haproxy-rmp

- src: https://github.com/carlosfrias/apigee-opdk-server-self

- src: https://github.com/carlosfrias/apigee-opdk-cwc-update

- src: https://github.com/carlosfrias/apigee-opdk-modules

